### ISSUE TITLE
Please remove smelting recipe for thermal cinnibar into thaumcraft quicksilver

### ISSUE THREAD

**Issue by alexbobp** [copygirl/obsidian_packs#15]
I guess because thaumcraft has "cinnibar ore," forge decided cinnibar is cinnibar.  Thing is, thermal cinnibar is a lot more valuable, and running pulverizer output into smelting is relatively common.

**Comment by copygirl** [comment]
I would guess this is an issue with UniDict trying to unify the different cinnabars.
