### ISSUE TITLE
Provide alternate recipes for "Fuelium"

### ISSUE THREAD

**Issue by copygirl** [copygirl/obsidian_packs#17]
Currently, fuelium from [MrCrayfish's Vehicle Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod) requires using its own fluid extractor, which produces its own ender sap and blaze juice fluids; and fluid mixer, which takes those two to make the final fuelium fluid.

It doesn't appear to be possible to add other valid fuels for the vehicles, so instead we should add recipes to turn existing fluids that would fit (such as gasoline) into fuelium.

**Comment by alexbobp** [comment]
uranium.
